// <auto-generated />
using System;
using AarhusSpaceProgram.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AarhusSpaceProgram.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260325115248_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AarhusSpaceProgram.Api.Models.Astronaut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("HoursInSpace")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Astronauts");
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Models.CelestialBody", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("CelestialBodies");
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Models.Launchpad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Launchpads");
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Models.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Models.Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("LaunchDate")
                        .HasColumnType("date");

                    b.Property<int?>("LaunchpadId")
                        .HasColumnType("int");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("RocketId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TargetCelestialBodyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("RocketId")
                        .IsUnique()
                        .HasFilter("[RocketId] IS NOT NULL");

                    b.HasIndex("TargetCelestialBodyId");

                    b.HasIndex("LaunchpadId", "LaunchDate")
                        .IsUnique()
                        .HasFilter("[LaunchpadId] IS NOT NULL AND [LaunchDate] IS NOT NULL");

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Models.Rocket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Rockets");
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Models.Scientist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FieldOfExpertise")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Scientists");
                });

            modelBuilder.Entity("AstronautMission", b =>
                {
                    b.Property<int>("AstronautsId")
                        .HasColumnType("int");

                    b.Property<int>("MissionsId")
                        .HasColumnType("int");

                    b.HasKey("AstronautsId", "MissionsId");

                    b.HasIndex("MissionsId");

                    b.ToTable("MissionAstronauts", (string)null);
                });

            modelBuilder.Entity("MissionScientist", b =>
                {
                    b.Property<int>("MissionsId")
                        .HasColumnType("int");

                    b.Property<int>("ScientistsId")
                        .HasColumnType("int");

                    b.HasKey("MissionsId", "ScientistsId");

                    b.HasIndex("ScientistsId");

                    b.ToTable("MissionScientists", (string)null);
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Models.Mission", b =>
                {
                    b.HasOne("AarhusSpaceProgram.Api.Models.Launchpad", "Launchpad")
                        .WithMany("Missions")
                        .HasForeignKey("LaunchpadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AarhusSpaceProgram.Api.Models.Manager", "Manager")
                        .WithMany("Missions")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AarhusSpaceProgram.Api.Models.Rocket", "Rocket")
                        .WithOne("Mission")
                        .HasForeignKey("AarhusSpaceProgram.Api.Models.Mission", "RocketId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AarhusSpaceProgram.Api.Models.CelestialBody", "TargetCelestialBody")
                        .WithMany("Missions")
                        .HasForeignKey("TargetCelestialBodyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Launchpad");

                    b.Navigation("Manager");

                    b.Navigation("Rocket");

                    b.Navigation("TargetCelestialBody");
                });

            modelBuilder.Entity("AstronautMission", b =>
                {
                    b.HasOne("AarhusSpaceProgram.Api.Models.Astronaut", null)
                        .WithMany()
                        .HasForeignKey("AstronautsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AarhusSpaceProgram.Api.Models.Mission", null)
                        .WithMany()
                        .HasForeignKey("MissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MissionScientist", b =>
                {
                    b.HasOne("AarhusSpaceProgram.Api.Models.Mission", null)
                        .WithMany()
                        .HasForeignKey("MissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AarhusSpaceProgram.Api.Models.Scientist", null)
                        .WithMany()
                        .HasForeignKey("ScientistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Models.CelestialBody", b =>
                {
                    b.Navigation("Missions");
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Models.Launchpad", b =>
                {
                    b.Navigation("Missions");
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Models.Manager", b =>
                {
                    b.Navigation("Missions");
                });

            modelBuilder.Entity("AarhusSpaceProgram.Api.Models.Rocket", b =>
                {
                    b.Navigation("Mission");
                });
#pragma warning restore 612, 618
        }
    }
}
